CREATE TABLE `user`(email VARCHAR(100) NOT NULL , pwd VARCHAR(100) NOT NULL , PRIMARY KEY(email));

CREATE TABLE tweet(id int NOT NULL AUTO_INCREMENT, user_email VARCHAR(100) NOT NULL , text VARCHAR(255), PRIMARY KEY (id),
FOREIGN KEY (user_email) REFERENCES `user`(email) ON DELETE CASCADE);

