CREATE TABLE `user`(
id INT NOT NULL AUTO_INCREMENT,
email VARCHAR(100) NOT NULL UNIQUE,
pwd VARCHAR(100) NOT NULL ,
PRIMARY KEY(id));

CREATE TABLE tweet(
id int NOT NULL AUTO_INCREMENT,
user_email VARCHAR(100) NOT NULL ,
text VARCHAR(255), PRIMARY KEY (id),
FOREIGN KEY (user_email) REFERENCES `user`(email) ON DELETE CASCADE);

